# Generated by Django 3.2.4 on 2023-06-25 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('P_id', models.IntegerField(primary_key=True, serialize=False)),
                ('list_detial', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='About_SISFS',
            fields=[
                ('FD_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AboutHeading',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Sub_heading', models.CharField(max_length=200)),
                ('Detail_text', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='angelInvestorDB',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=2000)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ASIIM',
            fields=[
                ('L_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Reson', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='logo')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': ['image'],
            },
        ),
        migrations.CreateModel(
            name='Birac',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='UnTitled', max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.CharField(default='Author not provied any content', max_length=200)),
                ('overview', models.CharField(default='Author not provied any content', max_length=200)),
                ('image', models.ImageField(default='carrer/Screenshot_3.png', upload_to='Birac/%Y/%m/%d')),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='UnTitled', max_length=200)),
                ('description', models.CharField(default='Author not provied any description', max_length=200)),
                ('content', models.CharField(default='Author not provied any description', max_length=2000)),
                ('blog_profile_img', models.CharField(default='https://www.equalityhumanrights.com/sites/default/files/styles/listing_image/public/default_images/blog-teaser-default-full_5.jpg?itok=YOsTg-7X', max_length=2000)),
                ('categories', models.CharField(max_length=200)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BundledServices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Heading_1', models.CharField(max_length=200)),
                ('Content_1', models.CharField(max_length=200)),
                ('Heading_2', models.CharField(max_length=200)),
                ('Content_2', models.CharField(max_length=200)),
                ('Heading_3', models.CharField(max_length=200)),
                ('Content_3', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
                ('Name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='carrer/Screenshot_3.png', upload_to='Carrer/%Y/%m/%d')),
                ('Email', models.CharField(max_length=200)),
                ('Message', models.CharField(default='designation', max_length=200)),
                ('Subject', models.CharField(default='department', max_length=200)),
                ('qualififcation', models.CharField(default='qualififcation', max_length=200)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryforBlogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryforEvents',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryforExperience',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryforGallery',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryforQualification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryforStartups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryforTeams',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CentralGovernmentFundingDB',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=2000)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_SECTION',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=2000)),
                ('Address1', models.CharField(max_length=2000)),
                ('Address2', models.CharField(max_length=2000)),
                ('Phone_number', models.CharField(max_length=2000)),
                ('E_Mail', models.ImageField(default='carrer/Screenshot_3.png', upload_to='HOME_TESTIMONIAL/%Y/%m/%d')),
                ('mail', models.CharField(max_length=200)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ContactEditPage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('TextonImage', models.CharField(max_length=200)),
                ('SubHeading', models.CharField(max_length=200)),
                ('Address1', models.CharField(max_length=200)),
                ('Address2', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=200)),
                ('mail1', models.CharField(max_length=200)),
                ('mail2', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DemoDayPic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='DemoDayPic/%Y/%m/%d')),
                ('categories', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DemoDayTOPSECTION',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=200)),
                ('Content', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EDI_Eligibility_Section',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Sub_Heading', models.CharField(max_length=200)),
                ('point_1', models.CharField(max_length=200)),
                ('point_2', models.CharField(max_length=200)),
                ('point_3', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EDI_InnovationVoucher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=200)),
                ('Sub_Heading', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EDI_Overview_Section',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('point_1', models.CharField(max_length=200)),
                ('point_2', models.CharField(max_length=200)),
                ('point_3', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EDI_TOPSECTION',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Heading', models.CharField(max_length=200)),
                ('Sub_Heading', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='EDI_TOPSECTION/%Y/%m/%d')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EDI_WeAimAtSection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('point_1', models.CharField(max_length=200)),
                ('point_2', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('E_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='Events/%Y/%m/%d')),
                ('description', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EventsForm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='title', max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='carrer/Screenshot_3.png', upload_to='EventsForm/%Y/%m/%d')),
                ('Email', models.CharField(max_length=200)),
                ('company', models.CharField(default='company', max_length=200)),
                ('event', models.CharField(default='event', max_length=200)),
                ('linkedin', models.CharField(default='linkedin', max_length=200)),
                ('website', models.CharField(default='website', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities_developed',
            fields=[
                ('FD_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='fishieries',
            fields=[
                ('L_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Reson', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='logo')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': ['image'],
            },
        ),
        migrations.CreateModel(
            name='FooterEditPage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('InstituteName', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=200)),
                ('EXN', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('G_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='Gallery/%Y/%m/%d')),
                ('categories', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalMarket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Heading', models.CharField(max_length=200)),
                ('Content', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalMarketPic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='GlobalMarketPic/%Y/%m/%d')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Govt_Tie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='carrer/Screenshot_3.png', upload_to='Investors/%Y/%m/%d')),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HOME_TESTIMONIAL',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Testimonial_content', models.CharField(max_length=2000)),
                ('Name', models.CharField(max_length=2000)),
                ('Designation', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='carrer/Screenshot_3.png', upload_to='HOME_TESTIMONIAL/%Y/%m/%d')),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HomePdfLink',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=2000)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HowWeWork',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Sub_heading', models.CharField(max_length=200)),
                ('Point_1', models.CharField(max_length=200)),
                ('Point_2', models.CharField(max_length=200)),
                ('Point_3', models.CharField(max_length=200)),
                ('Point_4', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='HowWeWork/%Y/%m/%d')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='International_Partners',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='carrer/Screenshot_3.png', upload_to='Investors/%Y/%m/%d')),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Investors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='carrer/Screenshot_3.png', upload_to='Investors/%Y/%m/%d')),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IVP',
            fields=[
                ('L_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Reson', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='logo')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': ['image'],
            },
        ),
        migrations.CreateModel(
            name='JoinOurCommunity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=200)),
                ('Completed_Projects', models.CharField(max_length=200)),
                ('Satisfied_customers', models.CharField(max_length=200)),
                ('Expert_Employees', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LastContent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Sub_heading', models.CharField(max_length=200)),
                ('para_1', models.CharField(max_length=200)),
                ('para_2', models.CharField(max_length=200)),
                ('heading_1', models.CharField(max_length=200)),
                ('sub_para_1', models.CharField(max_length=200)),
                ('heading_2', models.CharField(max_length=200)),
                ('sub_para_2', models.CharField(max_length=200)),
                ('heading_3', models.CharField(max_length=200)),
                ('sub_para_3', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='LastContent/%Y/%m/%d')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Latest_News',
            fields=[
                ('L_id', models.IntegerField(primary_key=True, serialize=False)),
                ('News', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='logo',
            fields=[
                ('L_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Reson', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='logo')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': ['image'],
            },
        ),
        migrations.CreateModel(
            name='MBADB',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=2000)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MeitY_SAMRIDH',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Main_Heading', models.CharField(max_length=200)),
                ('Point_1', models.CharField(max_length=200)),
                ('Point_2', models.CharField(max_length=200)),
                ('Point_3', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MentorClinicDB',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=2000)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MentorConnectDB',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=2000)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='new_venturesDB',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=2000)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OurProcess',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=200)),
                ('concept_para', models.CharField(max_length=200)),
                ('prepare_para', models.CharField(max_length=200)),
                ('retouch_para', models.CharField(max_length=200)),
                ('video_link', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OurStartup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Sub_heading', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='OurStartup/%Y/%m/%d')),
                ('categories', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SamridthFund',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Main_Heading', models.CharField(max_length=200)),
                ('Sub_Heading', models.CharField(max_length=200)),
                ('Point_1', models.CharField(max_length=200)),
                ('Point_2', models.CharField(max_length=200)),
                ('Point_3', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='Start_UpTNimg2/%Y/%m/%d')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sisfs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='UnTitled', max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.CharField(default='Author not provied any content', max_length=200)),
                ('overview', models.CharField(default='Author not provied any content', max_length=200)),
                ('image', models.ImageField(default='carrer/Screenshot_3.png', upload_to='Sisfs/%Y/%m/%d')),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Twitter', models.CharField(max_length=200)),
                ('Facebook', models.CharField(max_length=200)),
                ('Instagram', models.CharField(max_length=200)),
                ('LinkedIn', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SpendingSection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=200)),
                ('Para_below_heading', models.CharField(max_length=200)),
                ('Point_1', models.CharField(max_length=200)),
                ('Point_2', models.CharField(max_length=200)),
                ('Point_3', models.CharField(max_length=200)),
                ('Point_4', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='GlobalMarketPic/%Y/%m/%d')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Start_UpTN',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Heading', models.CharField(max_length=200)),
                ('Content_1', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Start_UpTNContent2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Content_2', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Start_UpTNimg1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='Start_UpTNimg1/%Y/%m/%d')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Start_UpTNimg2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='Start_UpTNimg2/%Y/%m/%d')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StartupTN',
            fields=[
                ('L_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Reson', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='logo')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': ['image'],
            },
        ),
        migrations.CreateModel(
            name='StateGovtFund',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Main_Heading', models.CharField(max_length=200)),
                ('Sub_Heading', models.CharField(max_length=200)),
                ('Point_1', models.CharField(max_length=200)),
                ('Point_2', models.CharField(max_length=200)),
                ('Point_3', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StateGovtFundEligibilitySection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Sub_Heading', models.CharField(max_length=200)),
                ('Point_1', models.CharField(max_length=200)),
                ('Point_2', models.CharField(max_length=200)),
                ('Point_3', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StateGovtFundSecondSection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Main_Heading', models.CharField(max_length=200)),
                ('Sub_Heading', models.CharField(max_length=200)),
                ('Point_1', models.CharField(max_length=200)),
                ('Point_2', models.CharField(max_length=200)),
                ('Point_3', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='StateGovtFundSecondSection/%Y/%m/%d')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tbi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='UnTitled', max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.CharField(default='Author not provied any content', max_length=200)),
                ('overview', models.CharField(default='Author not provied any content', max_length=200)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='Team/%Y/%m/%d')),
                ('categories', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('T_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='Testimonials/%Y/%m/%d')),
                ('description', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TOPSECTION',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Heading', models.CharField(max_length=200)),
                ('Sub_Heading', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='GlobalMarketPic/%Y/%m/%d')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=2000)),
                ('content', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='carrer/Screenshot_3.png', upload_to='Investors/%Y/%m/%d')),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Sub_Heading', models.CharField(max_length=200)),
                ('Para_below_heading', models.CharField(max_length=200)),
                ('para_27', models.CharField(max_length=200)),
                ('Secure_Payment_para', models.CharField(max_length=200)),
                ('Daily_Update_para', models.CharField(max_length=200)),
                ('Market_Research_para', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WhoAreWe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('SubHeading', models.CharField(max_length=2000)),
                ('Point1', models.CharField(max_length=2000)),
                ('Point2', models.CharField(max_length=2000)),
                ('Point3', models.CharField(max_length=2000)),
                ('Point4', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='carrer/Screenshot_3.png', upload_to='WhoAreWe/%Y/%m/%d')),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
