# Generated by Django 3.2.4 on 2023-06-26 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourstartup_images',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Cmp_title', models.CharField(max_length=200)),
                ('special_at', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='OurStartup_logo/%Y/%m/%d')),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
