# Generated by Django 3.2.4 on 2023-06-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_mentor_lists_ourstartup_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourstartup_images',
            name='pre_incbu_or_incbu',
            field=models.CharField(max_length=200),
        ),
    ]
