# Generated by Django 3.2.4 on 2023-06-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_ourstartup_images_pre_incbu_or_incbu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourstartup_images',
            name='pre_incbu_or_incbu',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ourstartup_images',
            name='special_at',
            field=models.CharField(max_length=200),
        ),
    ]
