# Generated by Django 3.2.4 on 2023-06-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230626_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourstartup_images',
            name='special_at',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
