# Generated by Django 3.2.4 on 2023-07-13 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_center_of_excellance_design_and_development_healthcare_form_iot_form_support_servise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Scrolling_text',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('scrolling_text', models.CharField(max_length=300)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
