# Generated by Django 3.2.4 on 2023-07-14 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_home_scrolling_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_News_db',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('image_banner', models.ImageField(upload_to='Latest_news_bann/')),
                ('description', models.CharField(max_length=500)),
                ('uplode_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='New_Events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('image_banner', models.ImageField(upload_to='New_Events/')),
                ('description', models.CharField(max_length=500)),
                ('uplode_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Past_Events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('image_banner', models.ImageField(upload_to='Past_Events/')),
                ('description', models.CharField(max_length=500)),
                ('uplode_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
