# Generated by Django 3.2.4 on 2023-07-14 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_latest_news_db_new_events_past_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_Events',
            new_name='New_Events_db',
        ),
        migrations.RenameModel(
            old_name='Past_Events',
            new_name='Past_Events_db',
        ),
    ]
