# Generated by Django 3.2.4 on 2023-10-25 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_team_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Screen_banner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_banner', models.ImageField(upload_to='Home_Screen_banner/')),
                ('uplode_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
